### ISSUE TITLE
Home assistant 2026.3 changed the Lighting commands and broke the plugin

### ISSUE THREAD

**Issue by SquirrelRange** [corb3000/ha-artnet-led#20]
note the plugin works on 2026.2.x .

I am running 2026.3.4 on my test system and got this error. 

"Configuration warnings
Platform error 'light' from integration 'artnet_led' - cannot import name 'ATTR_COLOR_TEMP' from 'homeassistant.components.light' (/usr/src/homeassistant/homeassistant/components/light/__init__.py)"

it looks like they changed the names of "color_temp" to "color_temp_kelvin" along with some other light names. 

"Lights
Using 'color_temp' (in mireds) to set a light’s color temperature is no longer supported. Use 'color_temp_kelvin' instead.
Additionally, the 'color_temp', 'kelvin', 'min_mireds', and 'max_mireds' light entity state attributes have been removed. Use 'color_temp_kelvin', 'min_color_temp_kelvin', and 'max_color_temp_kelvin' instead."
https://www.home-assistant.io/blog/2026/03/04/release-20263/

I wonder if a find and replace might work for the new names. 

Thanks

**Comment by SquirrelRange** [comment]
Sorry i see @Breina has made a fork that works. i will move to that. 

Thanks for all your hard work.
